<?php

namespace AppBundle\Repository;

/**
 * CertificatMedicalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CertificatMedicalRepository extends \Doctrine\ORM\EntityRepository
{
}
