<?php

namespace AppBundle\Repository;

/**
 * PersonneContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonneContactRepository extends \Doctrine\ORM\EntityRepository
{
}
