<?php

namespace AppBundle\Repository;

/**
 * SaisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaisonRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Retourne toutes les saison
     *
     * @return array
     */
    public function listeAll(){
        return $this->createQueryBuilder('s')
            ->addOrderBy('s.annee')
            ->getQuery()
            ->getResult();
    }
}
